# Copyright (c) wilson.xu. All rights reserved.
import argparse
import time
from os.path import join
import json

from tqdm import tqdm
from diffusers.data.utils import json_save, load_file
from diffusers.data.byted.clients.azure_mllm import MLLMClient
from diffusers.data.byted.tos import save_file_to_tos


sys_prompt = "You are a professional quality inspector for AIGC-generated images and also a world-class artificial intelligence art director. Your task is to provide your evaluation result and reasons based on the given image and the following requirements (your answer should be in JSON format)."
prompt = """This is a product poster image generated by a large AIGC model. You need to conduct a quality inspection on the image in accordance with the following task requirements and provide your evaluation result and reasons.
Task Requirements:
1. Copywriting Spelling Errors: For the product name, primary selling points, and secondary selling points entered by the user, you need to locate their corresponding positions in the image and check whether the corresponding text in the image contains errors such as misspellings, missing characters, or repeated spellings. There is no need to pay attention to capitalization. Example: Rendered incorrectly: 'Super-Sof' is truncated (missing 't') and 'Fabric' is duplicated ('Fabric, Fabric,'), so there are spelling/duplication errors.
2. Defect Existence Errors: Check whether there are defects in the image. Example: defects on characters' hands/feet, product, or background etc.
3. If any of the above errors exist, answer "False" (bool type) along with the reasons; otherwise, answer "True" (bool type) to indicate that the image has passed the quality inspection. No need to provide reasons when the answer is True.
4. The copywriting inspection should not include the original text inherent to the product itself, such as the printed text on cans, the usage instructions on hand cream, the label text on the perfume bottle, and so on.
5. The answer should be in JSON format.

Quality Inspection Examples:
1. {'overall_evaluation_result': false, 'product_name': {'checking_result':true, 'reason':''}, 'primary_selling_points': {'checking_result':true, 'reason':''}, 'secondary_selling_points': {'checking_result':false, 'reason':'Each secondary selling point is repeated on the poster (appears twice) instead of only once.'}, 'defect_existence': {'checking_result':false, 'reason':'There are defects on the model\'s hands in the image'}}
2. {'overall_evaluation_result': true, 'product_name': {'checking_result':true, 'reason':''}, 'primary_selling_points': {'checking_result':true, 'reason':''}, 'secondary_selling_points': {'checking_result':true, 'reason':''}, 'defect_existence': {'checking_result':true, 'reason':''}}

Below is the product name, primary selling points, and secondary selling points:
"""


def parse_args():
    parser = argparse.ArgumentParser(description="inference script.")
    parser.add_argument(
        "--input_file",
        default=None,
        type=str,
        help="Path to image list on vos.")
    parser.add_argument(
        "--output_file",
        default="output_quality_inspection.json",
        type=str,
        help="Path to image list on vos.")
    parser.add_argument(
        "--image_dir",
        default="/mnt/bn/creative-algo/xsl/qwen_data_test",
        type=str)

    parser.add_argument(
        "--rank",
        default=None,
        type=int)
    parser.add_argument(
        "--num_ranks",
        default=None,
        type=int)

    args = parser.parse_args()

    return args


def main(args):
    gpt_client = MLLMClient(model_name="gpt-5-mini-2025-08-07")

    info_dict = load_file(args.input_file)
    if args.rank is not None and args.num_ranks is not None:
        assert args.rank < args.num_ranks
        info_dict = info_dict[args.rank::args.num_ranks]

    for item in tqdm(info_dict):
        try:
            input_text = {
                "product_name": item['product_name'],
                "primary_selling_points": item['primary_selling_points'],
                "secondary_selling_points": item['secondary_selling_points'],
            }
            user_prompt = prompt + json.dumps(input_text)
            predict_result = gpt_client.make_image_json_request(
                sys_prompt,
                user_prompt,
                image_paths=[join(args.image_dir, item['generate_image'])],
                max_tokens=5000,
            )
            for i in range(3):
                generate_url = save_file_to_tos(join(args.image_dir, item['generate_image']), item['generate_image'])
                if generate_url is not None:
                    item['generate_url'] = generate_url
                    break
                else:
                    time.sleep(1)
            item['result_quality_inspection'] = predict_result
        except Exception as e:
            print(item, e)

    json_save(info_dict, args.output_file)


if __name__ == "__main__":
    args = parse_args()
    main(args)
    print('Done!')
